name: "Ng-Components Library Versioning"

on:
  push:
    branches: [main]
    paths:
      - projects/components/**

concurrency:
  group: libs-versioning-group

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Npm install, build, and test
        run: |
          npm ci
          npm run build components
          npm run test -- components --source-map=false --browsers=ChromeHeadless --watch=false

  version:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Git user configuration
        run: |
          git config --global user.name 'RavinduSachintha'
          git config --global user.email '${{ secrets.RS_EMAIL }}'
          git config pull.rebase true

      - name: Initial git pull
        shell: bash
        run: git pull origin main

      - name: Npm version increment
        run: |
          cd ./projects/components
          mkdir .git
          npm version patch -m "[RELEASE] COMPONENTS %s"

      - name: Git pull & push
        shell: bash
        run: |
          git pull
          git push
